### ISSUE TITLE
When can we expect updates on this?

### ISSUE THREAD

**Issue by stefanmatar** [at-internet/atinternet-react-native-sample#1]
I have a few questions:

- How are you planning to develop this library? Is this a bridge between react and the corresponding AT-Internet native libraries or is the `react-native-at-wrapper` a standalone library?
- The readme under the wrapper is unfinished and has a TODO. Is there any timeframe we can expect this to change?

Thanks!

**Comment by BenDz** [comment]
Hey @stefanmatar, there is currently no plan to develop this library.
This repo is a sample of RN integration for our native SDKs, that must be adapted to each app requirements.
The TODO is aimed at the app devs, to remind them to add their needed bridges.
Best
